service: summer-of-speed
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi: '*'
